# Generated by Django 4.0.5 on 2022-06-18 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database_interface_api", "0002_alter_connection_connectionstring_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="connectionstring",
            field=models.CharField(max_length=250, verbose_name="Connection String"),
        ),
        migrations.AlterField(
            model_name="connection",
            name="connectiontype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="database_interface_api.connectiontype",
                verbose_name="Connection Type",
            ),
        ),
    ]
