# Generated by Django 4.0.5 on 2022-06-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database_interface_api", "0003_alter_connection_connectionstring_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectiontype",
            name="svg",
            field=models.FileField(blank=True, null=True, upload_to="media//admin"),
        ),
    ]
