# Generated by Django 4.0.5 on 2022-06-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database_interface_api", "0004_connectiontype_svg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectiontype",
            name="svg",
            field=models.FileField(blank=True, null=True, upload_to="admin/"),
        ),
    ]
