# Generated by Django 4.0.5 on 2022-07-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_interface_api', '0006_connection_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='credentials',
            field=models.FileField(blank=True, null=True, upload_to='admin/', verbose_name='Credentials File'),
        ),
        migrations.AddField(
            model_name='connection',
            name='host',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Host Name'),
        ),
        migrations.AddField(
            model_name='connection',
            name='port',
            field=models.IntegerField(blank=True, null=True, verbose_name='Port'),
        ),
        migrations.AddField(
            model_name='connection',
            name='sid',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='SID'),
        ),
        migrations.AddField(
            model_name='connection',
            name='user_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connectionstring',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Connection Name'),
        ),
    ]
