# Generated by Django 4.0.5 on 2022-07-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "database_interface_api",
            "0008_connection_schema_alter_connection_credentials",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Connection Name"),
        ),
    ]
