# Generated by Django 4.0.5 on 2022-07-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database_interface_api", "0009_alter_connection_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="port",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Port"
            ),
        ),
    ]
