# Generated by Django 4.0.5 on 2022-10-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database_interface_api", "0012_dataset_table_column"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="connectionstring",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Connection String"
            ),
        ),
    ]
