# Generated by Django 4.0.5 on 2022-06-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="forename",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(max_length=250),
        ),
    ]
