# Generated by Django 4.0.5 on 2022-06-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_forename_alter_user_surname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="sci07", max_length=255, unique=True, verbose_name="Username"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="forename",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(max_length=255),
        ),
    ]
