# Generated by Django 4.0.5 on 2022-06-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_username_alter_user_forename_alter_user_surname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
