# Generated by Django 4.0.5 on 2022-06-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="staff",
            field=models.BooleanField(default=False),
        ),
    ]
