# Generated by Django 4.0.5 on 2022-06-21 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_condition_field_history_jointype_logicoperator_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="condition",
            old_name="logi_operator",
            new_name="logic_operator",
        ),
    ]
