# Generated by Django 4.0.5 on 2022-06-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_logi_operator_condition_logic_operator"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobToTaskType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jobtype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.jobtype"
                    ),
                ),
                (
                    "tasktype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tasktype"
                    ),
                ),
            ],
        ),
    ]
