# Generated by Django 4.0.5 on 2022-06-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_jobtype_description_jointype_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtask",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
