# Generated by Django 4.0.5 on 2022-06-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_jobtask_staging_dataset_partition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="is_source_to_target",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="name",
            field=models.CharField(default="Name", max_length=255, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="field",
            name="source_column",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Source Column"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="source_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Source Table"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="transformation",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Column Transformation",
            ),
        ),
    ]
