# Generated by Django 4.0.5 on 2022-06-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_field_is_source_to_target_alter_field_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="join",
            name="task",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.jobtask",
            ),
            preserve_default=False,
        ),
    ]
