# Generated by Django 4.0.5 on 2022-06-21 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_join_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conditionfield",
            name="field",
        ),
        migrations.AddField(
            model_name="conditionfield",
            name="left",
            field=models.CharField(
                default=" ", max_length=255, verbose_name="Left Parameter"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conditionfield",
            name="right",
            field=models.CharField(
                default=" ", max_length=255, verbose_name="Right Parameter"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="condition",
            name="join",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.join",
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="where",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.jobtask",
            ),
        ),
        migrations.AlterField(
            model_name="join",
            name="left",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to default to driving table.",
                max_length=255,
                null=True,
                verbose_name="Left Table",
            ),
        ),
    ]
