# Generated by Django 4.0.5 on 2022-06-21 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_conditionfield_field_conditionfield_left_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditionfield",
            name="condition",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.condition"
            ),
        ),
    ]
