# Generated by Django 4.0.5 on 2022-06-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_join_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delta",
            name="upper_bound",
            field=models.IntegerField(
                help_text="Input seconds to add to lower_bound", null=True
            ),
        ),
        migrations.AlterField(
            model_name="jobtask",
            name="properties",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
