# Generated by Django 4.0.5 on 2022-06-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_dependency_options_alter_history_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operator",
            name="symbol",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
