# Generated by Django 4.0.5 on 2022-06-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_operator_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Job Name"),
        ),
    ]
