# Generated by Django 4.0.5 on 2022-06-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_jobtask_destination_dataset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtask",
            name="driving_table",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Driving Table"
            ),
        ),
    ]
