# Generated by Django 4.0.5 on 2022-07-01 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_jobtask_driving_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delta",
            name="lower_bound",
            field=models.CharField(
                help_text="Input a function that returns a date value or use preset;\n$YESTERDAY = today's date minus one day\n    $TODAY = today's date\n $THISWEEK = start date of current week, start date = MONDAY\n$THISMONTH = date of first day of current month\n",
                max_length=255,
                verbose_name="Lower Bound",
            ),
        ),
        migrations.AlterField(
            model_name="delta",
            name="upper_bound",
            field=models.IntegerField(
                help_text="Input seconds to add to lower_bound, 86400 represents one day",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="is_history_key",
            field=models.BooleanField(default=False, verbose_name="History Key Field"),
        ),
        migrations.AlterField(
            model_name="field",
            name="is_primary_key",
            field=models.BooleanField(
                default=False,
                help_text="Indictes the field is part of the table key.",
                verbose_name="Primary Key Field",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="source_name",
            field=models.CharField(
                blank=True,
                help_text="Source for the column, include dataset and table names: <dataset name>.<table name>",
                max_length=255,
                null=True,
                verbose_name="Source Table",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="name",
            field=models.SlugField(max_length=255, verbose_name="Job Name"),
        ),
        migrations.AlterField(
            model_name="jobtask",
            name="destination_dataset",
            field=models.CharField(
                blank=True,
                help_text="Enter the dataset containing the target table.",
                max_length=255,
                null=True,
                verbose_name="Destination Dataset",
            ),
        ),
        migrations.AlterField(
            model_name="jobtask",
            name="destination_table",
            field=models.CharField(
                help_text="Enter the destination table name.",
                max_length=255,
                verbose_name="Destination Table",
            ),
        ),
        migrations.AlterField(
            model_name="jobtask",
            name="driving_table",
            field=models.CharField(
                blank=True,
                help_text="Enter the driving table and dataset in format: <driving dataset name>.<driving table name>",
                max_length=255,
                null=True,
                verbose_name="Driving Table",
            ),
        ),
        migrations.AlterField(
            model_name="jobtask",
            name="properties",
            field=models.JSONField(
                blank=True,
                help_text="Enter additional task properties in JSON format.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobtask",
            name="staging_dataset",
            field=models.CharField(
                blank=True,
                help_text="Enter a staging dataset to be used for any pre-processing, can be left blank to default to Job value.",
                max_length=255,
                null=True,
                verbose_name="Staging Dataset",
            ),
        ),
        migrations.AlterField(
            model_name="jobtask",
            name="table_type",
            field=models.ForeignKey(
                default=1,
                help_text="Select desired SCD table type.",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="core.tabletype",
                verbose_name="Target Table Type",
            ),
        ),
        migrations.AlterField(
            model_name="jobtask",
            name="type",
            field=models.ForeignKey(
                default=1,
                help_text="Select task type.",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="core.tasktype",
                verbose_name="Task Type",
            ),
        ),
        migrations.AlterField(
            model_name="jobtask",
            name="write_disposition",
            field=models.ForeignKey(
                default=1,
                help_text="Select type of update to be performed on target table.",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="core.writedisposition",
                verbose_name="Write Disposition",
            ),
        ),
    ]
