# Generated by Django 4.0.5 on 2022-07-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_delta_lower_bound_alter_delta_upper_bound_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtask",
            name="name",
            field=models.SlugField(max_length=255, verbose_name="Task Name"),
        ),
    ]
