# Generated by Django 4.0.5 on 2022-07-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_batchjobproperties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchjobproperties',
            name='prefix',
            field=models.CharField(help_text='Enter the prefix which will be used for all tasks in this job; i.e. spine_order', max_length=255, verbose_name='Script Name Prefix'),
        ),
    ]
