# Generated by Django 4.0.5 on 2022-07-22 18:27

from django.db import migrations


def addtype2tabletype(apps, schema_editor):
    model = apps.get_model("core", "TableType")

    if not model.objects.filter(
        code="HISTORY",
    ).exists():
        model(
            name="Type 2",
            code="HISTORY",
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_field_data_type_alter_field_position"),
    ]

    operations = [
        migrations.RunPython(addtype2tabletype),
    ]
