# Generated by Django 4.0.5 on 2022-07-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_auto_20220722_1927"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcetable",
            name="alias",
            field=models.CharField(
                blank=True, max_length=255, unique=True, verbose_name="Table Alias"
            ),
        ),
        migrations.AddField(
            model_name="sourcetable",
            name="base_alias",
            field=models.CharField(
                blank=True,
                help_text="Non-unique alias, used to identify number of occurences of the table.",
                max_length=255,
                verbose_name="Base Table Alias",
            ),
        ),
        migrations.AlterField(
            model_name="historyorder",
            name="is_desc",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Is Descending?"
            ),
        ),
    ]
