# Generated by Django 4.0.5 on 2022-07-23 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_remove_field_source_name_join_left_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="join",
            name="left",
        ),
        migrations.RemoveField(
            model_name="join",
            name="right",
        ),
        migrations.AlterField(
            model_name="join",
            name="left_table",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="left_table",
                to="core.sourcetable",
                verbose_name="Left Table",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="join",
            name="right_table",
            field=models.ForeignKey(
                blank=True,
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="right_table",
                to="core.sourcetable",
                verbose_name="Right Table",
            ),
            preserve_default=False,
        ),
    ]
