# Generated by Django 4.0.5 on 2022-08-01 12:56

from django.db import migrations


def addisnullisnotnull(apps, schema_editor):
    model = apps.get_model("core", "Operator")

    if not model.objects.filter(
        code="NULL",
    ).exists():
        model(
            name="Is Null",
            symbol="is null",
            code="NULL",
        ).save()

    if not model.objects.filter(
        code="NOTNULL",
    ).exists():
        model(
            name="Is Not Null",
            symbol="is not null",
            code="NOTNULL",
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_batchjobproperties_target_project_and_more"),
    ]

    operations = [
        migrations.RunPython(addisnullisnotnull),
    ]
