# Generated by Django 4.0.5 on 2022-09-23 19:20

from django.db import migrations


def addinandnotin(apps, schema_editor):
    model = apps.get_model("core", "Operator")

    if not model.objects.filter(
        code="IN",
    ).exists():
        model(
            name="In",
            symbol="in",
            code="IN",
        ).save()

    if not model.objects.filter(
        code="NOTIN",
    ).exists():
        model(
            name="Not In",
            symbol="not in",
            code="NOTIN",
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_auto_20220801_1356"),
    ]

    operations = [
        migrations.RunPython(addinandnotin),
    ]
