name: Add issues to project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issues to project
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v0.4.0
        if: github.actor != 'dependabot[bot]'
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/users/sean-conkie/projects/3
          github-token: ${{ secrets.PROJECT_WORKFLOW_TOKEN }}
