name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
env:
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues to project 3
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        github.event.action == 'opened' &&
        github.event_name == 'issues'
      with:
        project: 'https://github.com/users/sean-conkie/projects/3'
        column_name: 'New'

    - name: Assign NEW pull_requests to project 3
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        github.event.action == 'opened' &&
        github.event_name == 'pull_request'
      with:
        project: 'https://github.com/users/sean-conkie/projects/3'
        column_name: 'In Progress'
        
        
